// frontend/src/lib/components/Card.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		children: Snippet;
		class?: string;
		onclick?: () => void;
	}

	let { children, class: className = '', onclick }: Props = $props();

	const base = 'rounded-xl border border-gray-200 bg-white p-4 shadow-sm transition-shadow';
</script>

{#if onclick}
	<button
		type="button"
		{onclick}
		class="{base} w-full cursor-pointer text-left active:shadow-md {className}"
	>
		{@render children()}
	</button>
{:else}
	<div class="{base} {className}">
		{@render children()}
	</div>
{/if}

// frontend-react/src/components/ui/Card.tsx
import type { ReactNode } from "react";

interface CardProps {
  children: ReactNode;
  className?: string;
  onClick?: () => void;
}

export function Card({ children, className = "", onClick }: CardProps) {
  return (
    <div
      role={onClick ? "button" : undefined}
      tabIndex={onClick ? 0 : undefined}
      onClick={onClick}
      onKeyDown={(e) => {
        if (onClick && (e.key === "Enter" || e.key === " ")) onClick();
      }}
      className={`rounded-xl border border-gray-200 bg-white p-4 shadow-sm transition-shadow ${
        onClick ? "cursor-pointer active:shadow-md" : ""
      } ${className}`}
    >
      {children}
    </div>
  );
}
